print("=" * 60)
print("OpenMAIC 智能课堂服务")
print("=" * 60)
print()
print("此服务需要 Node.js >= 20 和 pnpm >= 10 环境。")
print()
print("安装步骤:")
print("  1. 安装 Node.js:  conda install -c conda-forge nodejs=20")
print("  2. 安装 pnpm:     corepack enable && corepack prepare pnpm@latest --activate")
print("  3. 安装依赖:      cd backend/OpenMAIC && pnpm install")
print("  4. 启动服务:      pnpm dev")
print()
print("服务将在 http://localhost:5006 上运行")
print("=" * 60)
